name: Check

on:
  workflow_dispatch: ~
  push:
    branches: [main, '*.*.x']
  pull_request: ~

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make check
